# fly.toml app configuration file generated for efoil on 2025-08-02T19:07:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'efoil'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'efoil_data_1'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
