# fly.toml app configuration file generated for app-empty-rain-635 on 2025-07-15T13:25:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-empty-rain-635'
primary_region = 'sin'

[experimental]
  auto_rollback = true

[build]

[deploy]
  strategy = 'immediate'

[env]
  PORT = '8080'

[processes]
  app = 'npm run start'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
